# Copyright (c) 2022-2023 Jonah Aragon <jonah@triplebit.net>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

INHERIT: mkdocs.common.yml
docs_dir: '../docs'
site_url: "https://www.privacyguides.org/en/"
site_dir: '../site/en'

site_name: Privacy Guides
site_description: |
  Privacy Guides is your central privacy and security resource to protect yourself online.
copyright: |
  <b>Privacy Guides</b> is a non-profit, socially motivated website that provides information for protecting your data security and privacy.<br>
  We do not make money from recommending certain products, and we do not use affiliate links.<br>
  &copy; 2019 - 2023 Privacy Guides and contributors.
  <a href="https://www.privacyguides.org/license"><strong>This website is open source</strong></a>.
edit_uri: edit/main/docs/

extra:
  generator: false
  analytics:
    provider: plausible
    property: privacyguides.org
    feedback:
      title: "Was this page helpful?"
      ratings:
        - icon: material/robot-happy-outline
          name: "This page was helpful"
          data: Helpful
          note: "Thanks for your feedback!"
        - icon: material/robot-confused
          name: "This page could be improved"
          data: Needs Improvement
          note: "Thanks for your feedback! Help us improve this page by opening a <a href='https://discuss.privacyguides.net/'>discussion on our forum</a>."

theme:
  language: en
  logo: ../theme/assets/brand/SVG/Logo/privacy-guides-logo-notext-colorbg.svg
  font:
    text: Public Sans
    code: DM Mono
  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      accent: deep purple
      toggle:
        icon: material/brightness-auto
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: amber
      toggle:
        icon: material/brightness-2
        name: "Switch to light mode"
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: deep purple
      toggle:
        icon: material/brightness-5
        name: "Switch to system theme"

plugins:
  social:
    cards: !ENV [NETLIFY, false]
    cards_color:
      fill: "#FFD06F"
      text: "#2d2d2d"
    cards_dir: assets/img/social
    cards_font: Public Sans
    cache_dir: .cache/plugin/social-en

markdown_extensions:
  pymdownx.snippets:
    auto_append: 
      - includes/abbreviations.en.txt

nav:
  - Home: 'index.md'
  - Knowledge Base:
    - 'basics/threat-modeling.md'
    - 'basics/common-threats.md'
    - 'basics/common-misconceptions.md'
    - 'basics/account-creation.md'
    - 'basics/account-deletion.md'
    - Technology Essentials:
      - 'basics/passwords-overview.md'
      - 'basics/multi-factor-authentication.md'
      - 'basics/email-security.md'
      - 'basics/vpn-overview.md'
    - Operating Systems:
      - 'os/android-overview.md'
      - 'os/linux-overview.md'
      - 'os/qubes-overview.md'
    - Advanced Topics:
      - 'advanced/dns-overview.md'
      - 'advanced/tor-overview.md'
      - 'advanced/payments.md'
      - 'advanced/communication-network-types.md'
    - kb-archive.md
  - Recommendations:
    - 'tools.md'
    - Internet Browsing:
      - 'tor.md'
      - 'desktop-browsers.md'
      - 'mobile-browsers.md'
    - Operating Systems:
      - 'android.md'
      - 'desktop.md'
      - 'router.md'
    - Providers:
      - 'cloud.md'
      - 'dns.md'
      - 'email.md'
      - 'financial-services.md'
      - 'search-engines.md'
      - 'vpn.md'
    - Software:
      - 'calendar.md'
      - 'cryptocurrency.md'
      - 'data-redaction.md'
      - 'email-clients.md'
      - 'encryption.md'
      - 'file-sharing.md'
      - 'frontends.md'
      - 'multi-factor-authentication.md'
      - 'news-aggregators.md'
      - 'notebooks.md'
      - 'passwords.md'
      - 'productivity.md'
      - 'real-time-communication.md'
      - 'video-streaming.md'
  - About:
    - 'about/index.md'
    - 'about/criteria.md'
    - 'about/statistics.md'
    - 'about/notices.md'
    - 'about/privacy-policy.md'
    - Community:
      - 'about/donate.md'
      - Online Services: 'about/services.md'
      - Code of Conduct: 'CODE_OF_CONDUCT.md'
      - 'about/privacytools.md'
    - Contributing:
      - Writing Guide:
        - 'meta/writing-style.md'
        - 'meta/brand.md'
      - Technical Guides:
        - 'meta/uploading-images.md'
        - 'meta/git-recommendations.md'
  - Changelog: 'https://github.com/privacyguides/privacyguides.org/releases'
  - Forum: 'https://discuss.privacyguides.net/'
  - Blog: 'https://blog.privacyguides.org/'
